batch-to-kafka-service:
  twitter-Keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
kafka-config:
  bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
  shcema-registry-url-key: shema.registry.url
  shcema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    -twitter-topic
  num-of-partitions: 3
  replication-factor: 3
kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  ack: all
  batch-size: 16384
  batch-size-boost-factor: 100
  liner-ms: 5
  request-timeout-ms: 60000
  retry-count: 5
retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 10000
